### ISSUE TITLE
Security Concerns

### ISSUE THREAD

**Issue by jdeal-mediamath** [mykeels/slack-theme-cli#6]
The following line of injection is vulnerable:

```
\$('<style></style>').appendTo('head').html(css + overrides);
```

I suggest changing `.html()` to `.text()` to prevent anyone from tampering with the source css files and inject logging or something malicious when `.html()` executes the css. Since `.text()` does not execute anything, this would prevent injection attacks.

**Comment by mykeels** [comment]
Hi @jdeal-mediamath 

Thanks for raising this issue. 

I fail to see where the malicious attack would come from. Could you please explain?

**Comment by jdeal-mediamath** [comment]
Its more since the css it loads is stored in a remote CDN, it is vulnerable to being edited to include something malicious like a keylogger (see https://github.com/maxchehab/CSS-Keylogging). In fact, this suggests to me that even replacing `.html()` with `.text()` doesn't fix this. The best solution would be making the loaded CSS a part of this repository so that there is more visibility and control.

**Comment by mykeels** [comment]
The CSS files are already on a public GitHub repo with a commit history.

**Comment by kkirby** [comment]
For example, if someone were to change this file:

https://raw.githubusercontent.com/laCour/slack-night-mode/master/arc-dark.css

To be malicious in intent. Your plugin would pull maliciously modified file and inject it into a style tag using `.html()`, the Slack app has now been compromised. By using `.text()` instead of `.html()` it will ensure that the contents won't be parsed as HTML.

Does that make sense?

**Comment by mykeels** [comment]
I just checked, and

```js
$('<style></style>').appendTo('head').html(`</style>
<script>console.log('hello world');</script>
<style>
.btn {
	background-color: red;
}
`)
```

actually runs the script.

Thanks! I'll update to use `text(...)` instead.
